### ISSUE TITLE
Extension resets workbench.tree.indent

### ISSUE THREAD

**Issue by manuelbieh** [Microsoft/vscode-atom-keybindings#58] opened 2019-02-13 13:20 UTC
The Atom Keybindings extension causes the `workbench.tree.indent` setting to be reset to its default once it is enabled. I was able to reproduce it and Atom Keybindings really seems to be the cause for that (see the gif below).

It doesn't matter if it's specified in workspace or user settings or both. Once I enable the Atom Keybindings my filetree isn't indented according to my settings anymore:

![indent](https://user-images.githubusercontent.com/239546/52714290-cb5ecc00-2f99-11e9-8f8e-c8a22ab3efe9.gif)

The problem also occurs when closing and restarting the editor. I see my 20px indentation for a brief moment then the extension seems to be loaded and the indentation jumps back to 8px.

**Comment by egamma** [comment] 2019-02-18 08:57
//CC @joaomoreno

**Comment by joaomoreno** [comment] 2019-02-18 09:43
Dupe of https://github.com/Microsoft/vscode/issues/68742

**Closed by joaomoreno** 2019-02-18 09:43 UTC
