### ISSUE TITLE
Windows: fold / unfold shortcuts not working

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-atom-keybindings#7] opened 2016-10-25 10:30 UTC
Testing Microsoft/vscode#14318:

Fold / unfold shortcuts not working on windows

**Comment by chrisdias** [comment] 2020-05-03 19:47
i can't reproduce this, closing.

**Closed by chrisdias** 2020-05-03 19:47 UTC
Labels: bug

**Comment by isidorn** [comment] 2020-05-04 08:12
@chrisdias nice 4 year triage period :D
